import {
  Rocket,
  LayoutGrid,
  Sparkles,
  ShoppingBag,
  TrendingUp,
  Megaphone,
  Newspaper,
  Instagram as InstagramIcon,
  Quote,
  Mail,
  Image as ImageIcon,
  Type,
  Package,
  Video,
  Images,
  MessageSquare,
  Code2,
  PencilRuler,
  Megaphone as AnnouncementIcon,
  Menu,
  PanelBottom,
  Heading,
  Grid2x2,
  FolderTree,
  Car,
  Columns2,
  Split,
  HelpCircle,
  BookOpen,
  Search,
  Heart,
  ShoppingCart,
  CreditCard,
  UserCircle,
  FormInput,
  Eye,
  ListFilter,
} from 'lucide-react';
import type { SectionTypeMeta } from './types';

/**
 * One canonical registry of every section the Visual Builder can compose —
 * mirroring what the storefront actually renders.
 *
 * - `homepage` sections live in `settings.homepageSections` (hero + campaign
 *   banners live in their own collections).
 * - `layout` sections (announcement bar, navbar, footer) render on every page.
 * - `live` sections mirror real storefront sections that pull live API data
 *   (products, collections, categories, blogs, reviews, FAQs).
 * - remaining `pages` sections persist to Page documents.
 */
export const SECTION_TYPES: SectionTypeMeta[] = [
  // --- Layout (rendered on every storefront page) --------------------------
  {
    type: 'announcement-bar',
    label: 'Announcement Bar',
    icon: AnnouncementIcon,
    configurable: false,
    layout: true,
    live: true,
    liveLabel: '{count} message(s) live',
    scope: 'all',
    description: 'Top marquee rendered on every page. Messages are configured in Theme → Announcement Bar.',
  },
  {
    type: 'navbar',
    label: 'Navbar',
    icon: Menu,
    configurable: false,
    layout: true,
    live: true,
    liveLabel: '{count} nav link(s)',
    scope: 'all',
    description: 'Fixed storefront header rendered on every page. Links are configured in Theme → Navbar.',
  },
  {
    type: 'footer',
    label: 'Footer',
    icon: PanelBottom,
    configurable: false,
    layout: true,
    live: true,
    liveLabel: '{count} footer link(s)',
    scope: 'all',
    description: 'Storefront footer rendered on every page. Configured in Theme → Footer.',
  },

  // --- Homepage ------------------------------------------------------------
  {
    type: 'hero',
    label: 'Hero',
    icon: Rocket,
    configurable: true,
    entity: 'hero',
    scope: 'homepage',
    description: 'Rotating hero slider. Manage hero sets — slides, scheduling, CTAs and ordering — right from this section.',
  },
  {
    type: 'luxuryCategories',
    label: 'Luxury Categories',
    icon: LayoutGrid,
    configurable: false,
    live: true,
    liveLabel: '{count} categories live',
    scope: 'homepage',
    description: 'Category showcase. Renders live category data automatically.',
  },
  {
    type: 'featuredCollections',
    label: 'Featured Collections',
    icon: Sparkles,
    configurable: false,
    live: true,
    liveLabel: '{count} collections live',
    scope: 'homepage',
    description: 'Featured collection tiles from the storefront catalog.',
  },
  {
    type: 'newArrivals',
    label: 'New Arrivals',
    icon: ShoppingBag,
    configurable: false,
    live: true,
    liveLabel: 'live product data',
    scope: 'homepage',
    description: 'Latest products grid. Renders live product data automatically.',
  },
  {
    type: 'bestSellers',
    label: 'Best Sellers',
    icon: TrendingUp,
    configurable: false,
    live: true,
    liveLabel: 'live order data',
    scope: 'homepage',
    description: 'Top selling products from live order data.',
  },
  {
    type: 'trending',
    label: 'Trending',
    icon: ImageIcon,
    configurable: false,
    live: true,
    liveLabel: 'live storefront data',
    scope: 'homepage',
    description: 'Trending products from live storefront data.',
  },
  {
    type: 'campaign-banner',
    label: 'Campaign Banner',
    icon: Megaphone,
    configurable: true,
    entity: 'banner',
    scope: 'homepage',
    description: 'Seasonal campaign banner. Manage banners — artwork, links, targeting and schedule — right from this section.',
  },
  {
    type: 'journal',
    label: 'Journal Preview',
    icon: Newspaper,
    configurable: false,
    live: true,
    liveLabel: '{count} posts live',
    scope: 'homepage',
    description: 'Latest journal posts. Renders live blog data automatically.',
  },
  {
    type: 'customerReviews',
    label: 'Customer Reviews',
    icon: Quote,
    configurable: false,
    live: true,
    liveLabel: '{count} reviews live',
    scope: 'homepage',
    description: 'Customer testimonials. Renders live review data automatically.',
  },
  {
    type: 'editorial',
    label: 'Editorial Banner',
    icon: Newspaper,
    configurable: true,
    scope: 'all',
    description: 'Full-width editorial with image, headline, copy and two CTAs.',
  },
  {
    type: 'instagram',
    label: 'Instagram Gallery',
    icon: InstagramIcon,
    configurable: true,
    scope: 'all',
    description: 'Tiled gallery of Instagram posts with optional profile link.',
  },
  {
    type: 'newsletter',
    label: 'Newsletter',
    icon: Mail,
    configurable: true,
    scope: 'all',
    description: 'Email capture band with heading, copy and form labels.',
  },

  // --- Live-data page sections (mirror real storefront rendering) ----------
  {
    type: 'page-header',
    label: 'Page Header',
    icon: Heading,
    configurable: false,
    live: true,
    liveLabel: 'page title, eyebrow & breadcrumb',
    scope: 'all',
    description: 'Header band with eyebrow, title, description and breadcrumb — rendered by the storefront page.',
  },
  {
    type: 'collection-grid',
    label: 'Collection Grid',
    icon: Grid2x2,
    configurable: false,
    live: true,
    liveLabel: '{count} collections live',
    scope: 'all',
    description: 'Responsive grid of collection cards rendered from live catalog data.',
  },
  {
    type: 'category-grid',
    label: 'Category Grid',
    icon: FolderTree,
    configurable: false,
    live: true,
    liveLabel: '{count} categories live',
    scope: 'all',
    description: 'Category tiles rendered from the live category tree.',
  },
  {
    type: 'category-filter',
    label: 'Category Filter',
    icon: ListFilter,
    configurable: false,
    live: true,
    liveLabel: 'live category & price filters',
    scope: 'all',
    description: 'Storefront filter panel (categories, price range, sort).',
  },
  {
    type: 'product-carousel',
    label: 'Product Carousel',
    icon: Car,
    configurable: false,
    live: true,
    liveLabel: 'live product data',
    scope: 'all',
    description: 'Horizontal product carousel rendered from live product data.',
  },
  {
    type: 'collection-carousel',
    label: 'Collection Carousel',
    icon: Columns2,
    configurable: false,
    live: true,
    liveLabel: '{count} collections live',
    scope: 'all',
    description: 'Collection carousel rendered from live catalog data.',
  },
  {
    type: 'blog-preview',
    label: 'Blog Preview',
    icon: BookOpen,
    configurable: false,
    live: true,
    liveLabel: '{count} posts live',
    scope: 'all',
    description: 'Blog post grid rendered from live journal data.',
  },
  {
    type: 'faq',
    label: 'FAQ Section',
    icon: HelpCircle,
    configurable: false,
    live: true,
    liveLabel: '{count} FAQs live',
    scope: 'all',
    description: 'FAQ accordion rendered from live FAQ data.',
  },
  {
    type: 'cart-items',
    label: 'Cart Line Items',
    icon: ShoppingCart,
    configurable: false,
    live: true,
    liveLabel: 'live cart lines',
    scope: 'all',
    description: 'Cart line items list rendered by the storefront cart page.',
  },
  {
    type: 'order-summary',
    label: 'Order Summary',
    icon: CreditCard,
    configurable: false,
    live: true,
    liveLabel: 'live totals & discounts',
    scope: 'all',
    description: 'Order totals card (subtotal, shipping, tax, total) rendered by cart/checkout.',
  },
  {
    type: 'checkout-form',
    label: 'Checkout Form',
    icon: FormInput,
    configurable: false,
    live: true,
    liveLabel: 'live shipping & payment steps',
    scope: 'all',
    description: 'Multi-step checkout (shipping → payment) rendered by the storefront.',
  },
  {
    type: 'contact-form',
    label: 'Contact Form',
    icon: MessageSquare,
    configurable: false,
    live: true,
    liveLabel: 'live contact form',
    scope: 'all',
    description: 'Contact enquiry form rendered by the storefront contact page.',
  },
  {
    type: 'account-dashboard',
    label: 'Account Dashboard',
    icon: UserCircle,
    configurable: false,
    live: true,
    liveLabel: 'live orders, wishlist & profile',
    scope: 'all',
    description: 'Account navigation and dashboard tiles rendered by the storefront.',
  },
  {
    type: 'search-results',
    label: 'Search Results',
    icon: Search,
    configurable: false,
    live: true,
    liveLabel: 'live search results',
    scope: 'all',
    description: 'Product results grid rendered from live search data.',
  },
  {
    type: 'wishlist-grid',
    label: 'Wishlist Grid',
    icon: Heart,
    configurable: false,
    live: true,
    liveLabel: 'live wishlist items',
    scope: 'all',
    description: 'Saved products grid rendered by the storefront wishlist page.',
  },

  // --- Configurable page sections (persist to Page documents) --------------
  {
    type: 'text',
    label: 'Text Block',
    icon: Type,
    configurable: true,
    scope: 'pages',
    description: 'Heading, subheading and rich text body.',
  },
  {
    type: 'product-grid',
    label: 'Product Grid',
    icon: Package,
    configurable: true,
    scope: 'pages',
    description: 'A curated product grid with title and optional source.',
  },
  {
    type: 'banner',
    label: 'Image Banner',
    icon: Megaphone,
    configurable: true,
    scope: 'pages',
    description: 'Full-width image banner with optional link.',
  },
  {
    type: 'split-banner',
    label: 'Split Banner',
    icon: Split,
    configurable: true,
    scope: 'pages',
    description: 'Two-column image + copy banner with CTA.',
  },
  {
    type: 'video',
    label: 'Video',
    icon: Video,
    configurable: true,
    scope: 'pages',
    description: 'Embedded video file with optional poster.',
  },
  {
    type: 'video-banner',
    label: 'Video Banner',
    icon: Video,
    configurable: true,
    scope: 'pages',
    description: 'Full-width video banner with overlay copy.',
  },
  {
    type: 'image-gallery',
    label: 'Image Gallery',
    icon: Images,
    configurable: true,
    scope: 'pages',
    description: 'Grid of images from the media library.',
  },
  {
    type: 'testimonials',
    label: 'Testimonials',
    icon: MessageSquare,
    configurable: true,
    scope: 'pages',
    description: 'Customer testimonials block.',
  },
  {
    type: 'brand-story',
    label: 'Brand Story',
    icon: BookOpen,
    configurable: true,
    scope: 'pages',
    description: 'Brand narrative with image, copy and values.',
  },
  {
    type: 'custom',
    label: 'Custom HTML',
    icon: Code2,
    configurable: true,
    scope: 'pages',
    description: 'Arbitrary HTML for advanced layouts.',
  },
  {
    type: 'layout-block',
    label: 'Layout Block',
    icon: PencilRuler,
    configurable: true,
    scope: 'pages',
    description: 'Structural block with background, padding and CSS hooks.',
  },
  {
    type: 'seo',
    label: 'SEO',
    icon: Eye,
    configurable: true,
    scope: 'pages',
    description: 'Page SEO — meta title, description and keywords.',
  },
];

export function metaFor(type: string): SectionTypeMeta | undefined {
  return SECTION_TYPES.find((t) => t.type === type);
}

export function typesForScope(scope: 'homepage' | 'pages'): SectionTypeMeta[] {
  return SECTION_TYPES.filter((t) => t.scope === 'all' || t.scope === scope);
}

/** Section types that can never be persisted to a Page document / homepage
 * config because they are rendered by the layout or mirror live storefront
 * sections. */
export function isPersistable(type: string): boolean {
  const meta = metaFor(type);
  if (!meta) return false;
  if (meta.layout || meta.live) return false;
  return true;
}
