import { body, param } from 'express-validator';

const heroLinkValidation = (field: 'primaryButton' | 'secondaryButton') => [
  body(`${field}.label`).optional().trim(),
  body(`${field}.linkType`).optional().isIn(['collection', 'category', 'product', 'custom']).withMessage('Invalid link type'),
  body(`${field}.link`).optional().trim(),
];

export const createHeroValidation = [
  body('title').notEmpty().withMessage('Hero title is required').trim(),
  ...heroLinkValidation('primaryButton'),
  ...heroLinkValidation('secondaryButton'),
  body('subtitle').optional().trim(),
  body('description').optional().trim(),
  body('image').optional().trim(),
  body('video').optional().trim(),
  body('imageMobile').optional().trim(),
  body('videoMobile').optional().trim(),
  body('badge').optional().trim(),
  body('overlay').optional().isBoolean().withMessage('overlay must be a boolean'),
  body('overlayOpacity').optional().isInt({ min: 0, max: 100 }).withMessage('overlayOpacity must be 0-100'),
  body('gradient').optional().isBoolean().withMessage('gradient must be a boolean'),
  body('contentAlignment').optional().isIn(['left', 'center', 'right']).withMessage('Invalid content alignment'),
  body('textColor').optional().trim(),
  body('buttonColor').optional().trim(),
  body('accentColor').optional().trim(),
  body('animationStyle').optional().isIn(['slide', 'fade', 'kenburns']).withMessage('Invalid animation style'),
  body('animationSpeed').optional().isFloat({ min: 0.3, max: 4 }).withMessage('animationSpeed must be 0.3-4'),
  body('visibility.desktop').optional().isBoolean(),
  body('visibility.tablet').optional().isBoolean(),
  body('visibility.mobile').optional().isBoolean(),
  body('priority').optional().isInt().withMessage('priority must be an integer'),
  body('seoLabel').optional().trim(),
  body('altText').optional().trim(),
  body('status').optional().isIn(['draft', 'published']).withMessage('Invalid status'),
  body('isActive').optional().isBoolean().withMessage('isActive must be a boolean'),
  body('scheduledStart').optional().isISO8601().withMessage('Invalid scheduledStart date'),
  body('scheduledEnd').optional().isISO8601().withMessage('Invalid scheduledEnd date'),
];

export const updateHeroValidation = [
  param('id').isMongoId().withMessage('Invalid hero block ID'),
  body('title').optional().trim(),
  ...heroLinkValidation('primaryButton'),
  ...heroLinkValidation('secondaryButton'),
  body('subtitle').optional().trim(),
  body('description').optional().trim(),
  body('image').optional().trim(),
  body('video').optional().trim(),
  body('imageMobile').optional().trim(),
  body('videoMobile').optional().trim(),
  body('badge').optional().trim(),
  body('overlay').optional().isBoolean(),
  body('overlayOpacity').optional().isInt({ min: 0, max: 100 }),
  body('gradient').optional().isBoolean(),
  body('contentAlignment').optional().isIn(['left', 'center', 'right']),
  body('textColor').optional().trim(),
  body('buttonColor').optional().trim(),
  body('accentColor').optional().trim(),
  body('animationStyle').optional().isIn(['slide', 'fade', 'kenburns']),
  body('animationSpeed').optional().isFloat({ min: 0.3, max: 4 }),
  body('visibility.desktop').optional().isBoolean(),
  body('visibility.tablet').optional().isBoolean(),
  body('visibility.mobile').optional().isBoolean(),
  body('priority').optional().isInt(),
  body('seoLabel').optional().trim(),
  body('altText').optional().trim(),
  body('status').optional().isIn(['draft', 'published']),
  body('isActive').optional().isBoolean(),
  body('scheduledStart').optional().isISO8601(),
  body('scheduledEnd').optional().isISO8601(),
];

export const heroIdValidation = [param('id').isMongoId().withMessage('Invalid hero block ID')];
