import { body, param } from 'express-validator';

const slideValidators = [
  body('panels.*.slides.*.image').optional().trim(),
  body('panels.*.slides.*.imageMobile').optional().trim(),
  body('panels.*.slides.*.video').optional().trim(),
  body('panels.*.slides.*.videoMobile').optional().trim(),
  body('panels.*.slides.*.eyebrow').optional().trim(),
  body('panels.*.slides.*.heading').optional().trim(),
  body('panels.*.slides.*.headingColor').optional().trim(),
  body('panels.*.slides.*.showEyebrow').optional().isBoolean().withMessage('showEyebrow must be a boolean'),
  body('panels.*.slides.*.showCta').optional().isBoolean().withMessage('showCta must be a boolean'),
  body('panels.*.slides.*.ctaText').optional().trim(),
  body('panels.*.slides.*.ctaLinkType').optional().isIn(['collection', 'category', 'product', 'custom']).withMessage('Invalid CTA link type'),
  body('panels.*.slides.*.ctaLink').optional().trim(),
  body('panels.*.slides.*.description').optional().trim(),
  body('panels.*.slides.*.secondaryButtonText').optional().trim(),
  body('panels.*.slides.*.secondaryButtonLink').optional().trim(),
  body('panels.*.slides.*.backgroundColor').optional().trim(),
  body('panels.*.slides.*.animationType').optional().isIn(['fade', 'zoom', 'slide']).withMessage('Invalid animationType'),
  body('panels.*.slides.*.status').optional().isIn(['draft', 'published']).withMessage('Invalid slide status'),
  body('panels.*.slides.*.isActive').optional().isBoolean().withMessage('isActive must be a boolean'),
  body('panels.*.slides.*.scheduledStart').optional().isISO8601().withMessage('Invalid slide scheduledStart date'),
  body('panels.*.slides.*.scheduledEnd').optional().isISO8601().withMessage('Invalid slide scheduledEnd date'),
  body('panels.*.slides.*.altText').optional().trim(),
];

const panelValidators = [
  body('panels').optional().isArray({ max: 5 }).withMessage('A hero set can contain at most 5 panels'),
  body('panels.*.label').optional().trim(),
  body('panels.*.status').optional().isIn(['draft', 'published']).withMessage('Invalid panel status'),
  body('panels.*.isActive').optional().isBoolean().withMessage('isActive must be a boolean'),
  ...slideValidators,
];

export const createHeroValidation = [
  body('name').notEmpty().withMessage('Hero set name is required').trim(),
  ...panelValidators,
  body('overlay').optional().isBoolean().withMessage('overlay must be a boolean'),
  body('overlayOpacity').optional().isInt({ min: 0, max: 100 }).withMessage('overlayOpacity must be 0-100'),
  body('gradient').optional().isBoolean().withMessage('gradient must be a boolean'),
  body('animationSpeed').optional().isFloat({ min: 0.3, max: 4 }).withMessage('animationSpeed must be 0.3-4'),
  body('priority').optional().isInt().withMessage('priority must be an integer'),
  body('status').optional().isIn(['draft', 'published']).withMessage('Invalid status'),
  body('isActive').optional().isBoolean().withMessage('isActive must be a boolean'),
  /* Legacy flat fields (optional) */
  body('title').optional().trim(),
  body('subtitle').optional().trim(),
  body('description').optional().trim(),
  body('image').optional().trim(),
  body('video').optional().trim(),
  body('imageMobile').optional().trim(),
  body('videoMobile').optional().trim(),
  body('badge').optional().trim(),
  body('primaryButton.label').optional().trim(),
  body('primaryButton.linkType').optional().isIn(['collection', 'category', 'product', 'custom']).withMessage('Invalid link type'),
  body('primaryButton.link').optional().trim(),
  body('secondaryButton.label').optional().trim(),
  body('secondaryButton.linkType').optional().isIn(['collection', 'category', 'product', 'custom']).withMessage('Invalid link type'),
  body('secondaryButton.link').optional().trim(),
  body('contentAlignment').optional().isIn(['left', 'center', 'right']).withMessage('Invalid content alignment'),
  body('textColor').optional().trim(),
  body('buttonColor').optional().trim(),
  body('accentColor').optional().trim(),
  body('animationStyle').optional().isIn(['slide', 'fade', 'kenburns']).withMessage('Invalid animation style'),
  body('visibility.desktop').optional().isBoolean(),
  body('visibility.tablet').optional().isBoolean(),
  body('visibility.mobile').optional().isBoolean(),
  body('seoLabel').optional().trim(),
  body('altText').optional().trim(),
  body('scheduledStart').optional().isISO8601().withMessage('Invalid scheduledStart date'),
  body('scheduledEnd').optional().isISO8601().withMessage('Invalid scheduledEnd date'),
];

export const updateHeroValidation = [
  param('id').isMongoId().withMessage('Invalid hero block ID'),
  body('name').optional().trim(),
  ...panelValidators,
  body('overlay').optional().isBoolean(),
  body('overlayOpacity').optional().isInt({ min: 0, max: 100 }),
  body('gradient').optional().isBoolean(),
  body('animationSpeed').optional().isFloat({ min: 0.3, max: 4 }),
  body('priority').optional().isInt(),
  body('status').optional().isIn(['draft', 'published']),
  body('isActive').optional().isBoolean(),
  /* Legacy flat fields (optional) */
  body('title').optional().trim(),
  body('subtitle').optional().trim(),
  body('description').optional().trim(),
  body('image').optional().trim(),
  body('video').optional().trim(),
  body('imageMobile').optional().trim(),
  body('videoMobile').optional().trim(),
  body('badge').optional().trim(),
  body('primaryButton.label').optional().trim(),
  body('primaryButton.linkType').optional().isIn(['collection', 'category', 'product', 'custom']),
  body('primaryButton.link').optional().trim(),
  body('secondaryButton.label').optional().trim(),
  body('secondaryButton.linkType').optional().isIn(['collection', 'category', 'product', 'custom']),
  body('secondaryButton.link').optional().trim(),
  body('contentAlignment').optional().isIn(['left', 'center', 'right']),
  body('textColor').optional().trim(),
  body('buttonColor').optional().trim(),
  body('accentColor').optional().trim(),
  body('animationStyle').optional().isIn(['slide', 'fade', 'kenburns']),
  body('visibility.desktop').optional().isBoolean(),
  body('visibility.tablet').optional().isBoolean(),
  body('visibility.mobile').optional().isBoolean(),
  body('seoLabel').optional().trim(),
  body('altText').optional().trim(),
  body('scheduledStart').optional().isISO8601(),
  body('scheduledEnd').optional().isISO8601(),
];

export const heroIdValidation = [param('id').isMongoId().withMessage('Invalid hero block ID')];
